endroid_qr_code:
    writer: 'png'
    size: 300
    margin: 10
    error_correction_level: 'low'
    validate_result: false
#    logo_path: '%kernel.project_dir%/public/build/images/apple-touch-icon.png'