vich_uploader:
  db_driver: orm
  metadata:
    auto_detection: true
  mappings:
    ticket_adjunto:
      uri_prefix: "%app.path.ticket_adjunto%"
      upload_destination: "%kernel.project_dir%/public/uploads/tickets/adjuntos"
      namer: "vich_uploader.namer_uniqid"
    expedientes_internos:
      uri_prefix: "%app.path.expedientes_internos%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/internos"
      namer: "vich_uploader.namer_uniqid"
    expedientes_externos:
      uri_prefix: "%app.path.expedientes_externos%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/externos"
      namer: "vich_uploader.namer_uniqid"
    dictamen:
      uri_prefix: "%app.path.dictamenes%"
      upload_destination: "%kernel.project_dir%/public/uploads/dictamenes"
      namer: "vich_uploader.namer_uniqid"
    sanciones:
      uri_prefix: "%app.path.sanciones%"
      upload_destination: "%kernel.project_dir%/public/uploads/sanciones"
    documentos:
      uri_prefix: "%app.path.documentos%"
      upload_destination: "%kernel.project_dir%/public/uploads/documentos"
    varios:
      uri_prefix: "%app.path.varios%"
      upload_destination: "%kernel.project_dir%/public/uploads/varios"
    expedientes_anexos:
      uri_prefix: "%app.path.expedientes_anexos%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/anexos"
      namer: "vich_uploader.namer_uniqid"
    giros_anexos:
      uri_prefix: "%app.path.giros_anexos%"
      upload_destination: "%kernel.project_dir%/public/uploads/giros/anexos"
      namer: "vich_uploader.namer_uniqid"
    dictamenes_anexos:
      uri_prefix: "%app.path.dictamenes_anexos%"
      upload_destination: "%kernel.project_dir%/public/uploads/dictamenes/anexos"
      namer: "vich_uploader.namer_uniqid"
    orden_de_pago:
      uri_prefix: "%app.path.ordenes_de_pago%"
      upload_destination: "%kernel.project_dir%/public/uploads/ordenes_de_pago"
    sis_images:
      uri_prefix: "%app.path.sis_images%"
      upload_destination: "%kernel.project_dir%/public/uploads/sis_images"
    textos_definitivos_anexos:
      uri_prefix: "%app.path.textos_definitivos_anexos%"
      upload_destination: "%kernel.project_dir%/public/uploads/textos_definitivos/anexos"
      namer: "vich_uploader.namer_uniqid"
    rrhh_novedad:
      uri_prefix: "%app.path.rrhh_novedad%"
      upload_destination: "%kernel.project_dir%/public/uploads/rrhh/novedades"
      namer: "vich_uploader.namer_uniqid"
    rrhh_licencia:
      uri_prefix: "%app.path.rrhh_licencia%"
      upload_destination: "%kernel.project_dir%/public/uploads/rrhh/licencias"
      namer: "vich_uploader.namer_uniqid"
    rrmm_perfil:
      uri_prefix: "%app.path.rrmm_perfil%"
      upload_destination: "%kernel.project_dir%/public/uploads/rrmm/perfiles"
      namer: "vich_uploader.namer_uniqid"
    rrmm_diagnostico:
      uri_prefix: "%app.path.rrmm_diagnostico%"
      upload_destination: "%kernel.project_dir%/public/uploads/rrmm/diagnosticos"
      namer: "vich_uploader.namer_uniqid"
    anexo_giro:
      uri_prefix: "%app.path.anexo_giro%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/giros"
      namer: "vich_uploader.namer_uniqid"
    anexo_legislativo:
      uri_prefix: "%app.path.anexo_legislativo%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/legislativo"
      namer: "vich_uploader.namer_uniqid"
    anexo_secretaria:
      uri_prefix: "%app.path.anexo_secretaria%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/secretaria"
      namer: "vich_uploader.namer_uniqid"
    comunicados:
      uri_prefix: "%app.path.comunicados%"
      upload_destination: "%kernel.project_dir%/public/uploads/comunicados"
      namer: "vich_uploader.namer_uniqid"
    firmado:
      uri_prefix: "%app.path.firmado%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/comision/giro/"
      namer: "vich_uploader.namer_uniqid"
    definitivo:
      uri_prefix: "%app.path.definitivo%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/definitivo/"
      namer: "vich_uploader.namer_uniqid"
    digesto:
      uri_prefix: "%app.path.digesto%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/digesto/"
      namer: "vich_uploader.namer_uniqid"
    pedido:
      uri_prefix: "%app.path.pedido%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/pedido/"
      namer: "vich_uploader.namer_uniqid"
    rama:
      uri_prefix: "%app.path.rama%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/rama/"
      namer: "vich_uploader.namer_uniqid"
    paseDem:
      uri_prefix: "%app.path.paseDem%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/pasedem/"
      namer: "vich_uploader.namer_uniqid"
    caratula_proveido:
      uri_prefix: "%app.path.caratula_proveido%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/proveido/caratula/"
      namer: "vich_uploader.namer_uniqid"
    proveido:
      uri_prefix: "%app.path.proveido%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/proveido/"
      namer: "vich_uploader.namer_uniqid"
    proveido_cierre:
      uri_prefix: "%app.path.proveido_cierre%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/proveido/cierre/"
      namer: "vich_uploader.namer_uniqid"
    expedientes_dem:
      uri_prefix: "%app.path.expedientes_dem%"
      upload_destination: "%kernel.project_dir%/public/uploads/expedientes/dem"
      namer: "vich_uploader.namer_uniqid"
    no_conformidad_images:
      uri_prefix: /uploads/no_conformidad/images
      upload_destination: '%kernel.project_dir%/public/uploads/no_conformidad/images'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
    no_conformidad_docs:
      uri_prefix: /uploads/no_conformidad/docs
      upload_destination: '%kernel.project_dir%/public/uploads/no_conformidad/docs'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
    no_conformidad_adjuntos:
      uri_prefix: /uploads/no_conformidad/adjuntos
      upload_destination: '%kernel.project_dir%/public/uploads/no_conformidad/adjuntos'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
