version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgrest_network
    ports:
      - "5432:5432"  # Exponer el puerto 5432 en el contenedor al puerto 5432 en la máquina host

volumes:
  postgres_data:

networks:
  postgrest_network:
    driver: bridge
