<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BloqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloqueRepository extends EntityRepository
{
}
