<?php

namespace AppBundle\Repository;

/**
 * ContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactoRepository extends \Doctrine\ORM\EntityRepository
{
}
