<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Mocion;

/**
 * MocionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MocionRepository extends \Doctrine\ORM\EntityRepository
{
    public function siguienteNumero()
    {
        $query = $this->createQueryBuilder('m')
            ->where('m.activo  = true')
            ->orderBy('m.numero', 'DESC')
            ->setMaxResults(1)
            ->getQuery();


        $result = $query->getResult();
        if (!count($result)) {
            return 1;
        }

        return $result[0]->getNumero() + 1;
    }

    /**
     * @return Mocion|null
     */
    public function getEnVotacion()
    {
        $result = $this->createQueryBuilder('m')
            ->join('m.estado', 'e')
            ->where('m.activo = true')
            ->andWhere('e.slug = :slug')
            ->setParameter('slug', Mocion::ESTADO_EN_VOTACION)
            ->getQuery()
            ->getResult();

        if (count($result)) {
            return $result[0];
        }
        return null;
    }
}
