<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Mocion;

/**
 * MocionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MocionRepository extends \Doctrine\ORM\EntityRepository
{
    public function siguienteNumero()
    {
        $query = $this->createQueryBuilder('m')
            ->where('m.activo  = true')
            ->orderBy('m.numero', 'DESC')
            ->setMaxResults(1)
            ->getQuery();

        /** @var Mocion $mocion */
        $mocion = $query->getSingleResult();

        return $mocion->getNumero() + 1;
    }
}
