<?php

namespace AppBundle\Repository;

/**
 * OrdenDePagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenDePagoRepository extends \Doctrine\ORM\EntityRepository
{
	public function getQbAll( $filter = null ) {
		$qb = $this->createQueryBuilder( 'op' );
		if ( $filter ) {
			if ( isset( $filter['numero'] ) ) {
				$numero = $filter['numero'];
				$qb
					->where( "od.numero = :numero" );
				$qb->setParameter( 'numero', $numero );
			}

			if ( isset( $filter['decreto'] ) ) {
				$q = $filter['decreto'];
				$qb
					->join( 'od.decreto', 'e' )
					->andWhere( 'UPPER(e.numero) LIKE UPPER(:numeroExpediente)' )
					->setParameter( 'numeroExpediente', "%$q%" );
			}
		}

		return $qb;
	}
}
