<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Parametro;
use Doctrine\ORM\NonUniqueResultException;

/**
 * ParametroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametroRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->createQueryBuilder('p')
            ->where('p.activo = true')
            ->getQuery()
            ->getResult();
    }

    public function grupo($grupo)
    {
        return $this->createQueryBuilder('p')
            ->where('p.activo = true')
            ->andWhere('p.grupo = :grupo')
            ->setParameter('grupo', $grupo)
            ->orderBy('p.orden', 'ASC')
            ->addOrderBy('p.valor', 'ASC');
    }

    /**
     * @param $slug
     * @return null|Parametro
     */
    public function getBySlug($slug)
    {
        try {
            return $this->createQueryBuilder('p')
                ->where('p.activo = true')
                ->andWhere('p.slug = :slug')
                ->setParameter('slug', $slug)
                ->setMaxResults(1)
                ->getQuery()
                ->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {
            return null;
        }
    }
}
