<?php

namespace AppBundle\Repository;

/**
 * PersonaACargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaACargoRepository extends \Doctrine\ORM\EntityRepository
{
}
