<?php

namespace AppBundle\Repository;

/**
 * SesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SesionRepository extends \Doctrine\ORM\EntityRepository
{
}
