<?php

namespace AppBundle\Repository;

/**
 * TextoDefinitivoExpedienteAdjuntoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextoDefinitivoExpedienteAdjuntoRepository extends \Doctrine\ORM\EntityRepository
{
}
