<?php

namespace MesaEntradaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogExpedienteRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LogExpedienteRepository extends EntityRepository
{
}
