<?php

namespace App\Repository;

/**
 * AnexoExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnexoExpedienteRepository extends \Doctrine\ORM\EntityRepository
{
}
