<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AreaAdministrativaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaAdministrativaRepository extends EntityRepository
{
}
