<?php

namespace App\Repository;

/**
 * AsuntoEntradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsuntoEntradoRepository extends \Doctrine\ORM\EntityRepository
{
}
