<?php

namespace App\Repository;

/**
 * BoletinAsuntoEntradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoletinAsuntoEntradoRepository extends \Doctrine\ORM\EntityRepository
{
}
