<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CargoPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoPersonaRepository extends EntityRepository
{
    public function findActivos()
    {
        return $this->createQueryBuilder('cp')
            ->where('cp.activo = :activo')
            ->setParameter('activo', true)
            ->getQuery();
    }
}
