<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactoPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactoPersonaRepository extends EntityRepository
{
}
