<?php

namespace App\Repository;

/**
 * DecretoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecretoRepository extends \Doctrine\ORM\EntityRepository {
	public function getQbAll( $filter = null ) {
		$qb = $this->createQueryBuilder( 'd' );
		if ( $filter ) {
			if ( isset( $filter['numero'] ) ) {
				$numero = $filter['numero'];
				$qb
					->where( "d.numero = :numero" );
				$qb->setParameter( 'numero', $numero );
			}

			if ( isset( $filter['expediente'] ) ) {
				$q = $filter['expediente'];
				$qb
					->join( 'd.expediente', 'e' )
					->andWhere( 'UPPER(e.expediente) LIKE UPPER(:expediente)' )
					->setParameter( 'expediente', "%$q%" );
			}
		}

		return $qb;
	}
}
