<?php

namespace App\Repository;

/**
 * DependenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependenciaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDependenciasPorNombre($nombre, $limit = 10, $returnArray = false)
    {
        $qb = $this->createQueryBuilder('d');
        $qb
            ->where("upper(d.nombre) like upper(:nombre)");
        $qb->setParameter('nombre', '%' . $nombre . '%');

        $qb->setMaxResults($limit);

        if ($returnArray) {
            return $qb->getQuery()->getArrayResult();
        } else {
            return $qb->getQuery()->getResult();
        }
    }

    public function getQbAll($filter = null)
    {
        $qb = $this->createQueryBuilder('d');
        if ($filter) {
            $nombre = $filter['nombre'];
            $qb
                ->where("upper(d.nombre) like upper(:nombre)");
            $qb->setParameter('nombre', '%' . $nombre . '%');
        }

        return $qb;
    }
}
