<?php

namespace App\Repository;

/**
 * DictamenODRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictamenODRepository extends \Doctrine\ORM\EntityRepository
{
}
