<?php

namespace App\Repository;

/**
 * DictamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictamenRepository extends \Doctrine\ORM\EntityRepository
{

    public function getQbAll()
    {
        $qb = $this->createQueryBuilder('d');
        $qb->orderBy('d.id', 'DESC');
        return $qb;

    }

    public function getQbBuscar($data,$estado)
    {
        $qb = $this->getQbAll();
        $qb->join('d.expediente', 'expediente');
        if (isset($data['expediente'])) {
            $q = $data['expediente'];

            $qb->andWhere('UPPER(expediente.expediente) LIKE UPPER(:expediente)')
                ->setParameter('expediente', "%$q%");
        }
        if ($estado===true) {
            $qb->andWhere('d.aprobadoLegislativo = :estado')
                ->setParameter('estado', 1);
        }
        if ($estado===false) {

            $qb ->andWhere(

                    $qb->expr()->neq('d.aprobadoLegislativo', ':estado')
                
            )
                ->setParameter('estado', 1);
                
        }
        if ($estado===null) {
            $qb->andWhere('d.aprobadoLegislativo IS NULL');
        }
        return $qb;
}
    }
    
