<?php

namespace App\Repository;

/**
 * IniciadorExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IniciadorExpedienteRepository extends \Doctrine\ORM\EntityRepository
{
}
