<?php

namespace App\Repository;

/**
 * OrdenDePagoRendicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenDePagoRendicionRepository extends \Doctrine\ORM\EntityRepository
{
}
