<?php

namespace App\Repository;

/**
 * OrdenDelDiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenDelDiaRepository extends \Doctrine\ORM\EntityRepository
{
}
