<?php

namespace App\Repository;

/**
 * OrdenDePagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenDePagoRepository extends \Doctrine\ORM\EntityRepository {
	public function getQbAll( $filter = null ) {
		$qb = $this->createQueryBuilder( 'op' );
		if ( $filter ) {
			if ( isset( $filter['numero'] ) ) {
				$numero = $filter['numero'];
				$qb
					->where( "op.numero = :numero" );
				$qb->setParameter( 'numero', $numero );
			}

			if ( isset( $filter['decreto'] ) ) {
				$q = $filter['decreto'];
				$qb
					->join( 'od.decreto', 'e' )
					->andWhere( 'UPPER(e.numero) LIKE UPPER(:numeroExpediente)' )
					->setParameter( 'numeroExpediente', "%$q%" );
			}

			if ( isset( $filter['tipoOrdenPago'] ) ) {
				$q = $filter['tipoOrdenPago'];
				$qb
					->andWhere( 'op.tipoOrdenPago = :tipoOrdenPago' )
					->setParameter( 'tipoOrdenPago', $q );
			}

			if ( isset( $filter['numeroEstante'] ) ) {
				$q = $filter['numeroEstante'];
				$qb
					->andWhere( 'op.numeroEstante = :numeroEstante' )
					->setParameter( 'numeroEstante', $q );
			}

			if ( isset( $filter['numeroCaja'] ) ) {
				$q = $filter['numeroCaja'];
				$qb
					->andWhere( 'op.numeroCaja = :numeroCaja' )
					->setParameter( 'numeroCaja', $q );
			}

			if ( isset( $filter['numeroCaja'] ) ) {
				$q = $filter['numeroCaja'];
				$qb
					->andWhere( 'op.numeroCaja = :numeroCaja' )
					->setParameter( 'numeroCaja', $q );
			}
		}

		return $qb;
	}
}
