<?php

namespace App\Repository;

/**
 * PeriodoLegislativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoLegislativoRepository extends \Doctrine\ORM\EntityRepository
{
}
