<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaRepository extends EntityRepository {
	public function getPersonaPorDni( $dni, $limit = 10, $returnArray = false ) {
		$qb = $this->createQueryBuilder( 'p' );
		$qb
			->where( "upper(p.dni) like upper(:dni)" );
		$qb->setParameter( 'dni', '%' . $dni . '%' );

		$qb->setMaxResults( $limit );

		if ( $returnArray ) {
			return $qb->getQuery()->getArrayResult();
		} else {
			return $qb->getQuery()->getResult();
		}
	}

	public function getQbAll( $filter = null ) {
		$qb = $this->createQueryBuilder( 'p' );

		if ( $filter ) {
			if ( isset( $filter['nombre'] ) ) {
				$q = $filter['nombre'];
				$qb->andWhere( 'UPPER(p.nombre) LIKE UPPER(:nombre)' )
					->setParameter( 'nombre', "%$q%" );
			}

			if ( isset( $filter['apellido'] ) ) {
				$q = $filter['apellido'];
				$qb->andWhere( 'UPPER(p.apellido) LIKE UPPER(:apellido)' )
				   ->setParameter( 'apellido', "%$q%" );
			}
			if ( isset( $filter['dni'] ) ) {
				$q = $filter['dni'];
				$qb->andWhere( 'UPPER(p.dni) LIKE UPPER(:dni)' )
				   ->setParameter( 'dni', "%$q%" );
			}
		}

		return $qb;
	}

}
