<?php

namespace App\Repository;

/**
 * ProyectoBAERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoBAERepository extends \Doctrine\ORM\EntityRepository
{
}
