<?php

namespace App\Repository;

use App\Entity\Sesion;

/**
 * ProyectoBAERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoBAERepository extends \Doctrine\ORM\EntityRepository {

	public function findByExpedienteTimeline( $expediente ) {

		$qb = $this->createQueryBuilder( 'pb' );

		$qb->where( 'pb.expediente = :expediente' )
		   ->setParameter( 'expediente', $expediente );

		$qb->leftJoin( 'pb.giros', 'giros' );

		$qb->addOrderBy( 'giros.orden', 'DESC' );
		$qb->addOrderBy( 'giros.fechaGiro', 'ASC' );

		return $qb->getQuery()->getResult();

	}

	/**
	 * Cambios de cabecera registrados, del más reciente al más viejo.
	 */
	public function getQbCambiosDeCabecera( ?string $numero ) {
		$qb = $this->createQueryBuilder( 'pb' )
		           ->join( 'pb.boletinAsuntoEntrado', 'bae' )
		           ->join( 'bae.sesion', 's' )
		           ->join( 'pb.expediente', 'e' )
		           ->addSelect( 'bae', 's', 'e' )
		           ->where( 'pb.esCambioCabecera = true' )
		           ->orderBy( 's.fecha', 'DESC' )
		           ->addOrderBy( 'pb.id', 'DESC' );

		if ( $numero !== null && $numero !== '' ) {
			$qb->andWhere( 'e.expediente = :numero' )
			   ->setParameter( 'numero', $numero );
		}

		return $qb;
	}

	/**
	 * Proyectos del BAE de la sesión a los que se les puede cambiar la cabecera.
	 * Se excluyen los de tratamiento sobre tablas: no pasan por comisión.
	 *
	 * @return \App\Entity\ProyectoBAE[]
	 */
	public function findParaCambioDeCabecera( Sesion $sesion ) {
		return $this->createQueryBuilder( 'pb' )
		            ->join( 'pb.boletinAsuntoEntrado', 'bae' )
		            ->join( 'pb.expediente', 'e' )
		            ->addSelect( 'e' )
		            ->where( 'bae.sesion = :sesion' )
		            ->andWhere( '(pb.tratamientoSobretabla IS NULL OR pb.tratamientoSobretabla = false)' )
		            ->setParameter( 'sesion', $sesion )
		            ->orderBy( 'e.expediente', 'ASC' )
		            ->getQuery()
		            ->getResult();
	}

}
