<?php

namespace App\Repository;

/**
 * TextoDefinitivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextoDefinitivoRepository extends \Doctrine\ORM\EntityRepository
{
	public function getQbAll( $filter = null ) {
		$qb = $this->createQueryBuilder( 'td' );
		if ( $filter ) {
			if ( isset( $filter['numero'] ) ) {
				$numero = $filter['numero'];
				$qb
					->where( "td.numero = :numero" );
				$qb->setParameter( 'numero', $numero );
			}

			if ( isset( $filter['rama'] ) ) {
				$q = $filter['rama'];
				$qb
					->where( "td.rama = :rama" );
				$qb->setParameter( 'rama', $q );
			}

			if ( isset( $filter['aprobadoEnSesion'] ) ) {
				$q = $filter['aprobadoEnSesion'];
				$qb
					->andWhere( 'td.aprobadoEnSesion = :aprobadoEnSesion' )
					->setParameter( 'aprobadoEnSesion', $q );
			}
		}

		return $qb;
	}
}
