<?php

namespace App\Repository;

/**
 * TipoDecretoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDecretoRepository extends \Doctrine\ORM\EntityRepository
{
}
