<?php

namespace App\Repository;

/**
 * TipoOrdenPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoOrdenPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
