<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoExpedienteRepository extends EntityRepository
{
}
