<?php

namespace App\Repository;

/**
 * TipoProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoProyectoRepository extends \Doctrine\ORM\EntityRepository
{
}
