<?php

namespace App\Repository;

/**
 * TipoMayoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoMayoriaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(
            'activo' => 1
        ));
    }
}
