<?php

namespace App\Repository;

/**
 * VotacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotacionRepository extends \Doctrine\ORM\EntityRepository
{
}
