comision_index:
  path: /
  defaults: { _controller: App\Controller\ComisionController::index }
  methods: GET

comision_dictamen_new:
  path: /newdictamen/{id}
  defaults: { _controller: App\Controller\ComisionController::newdictamen }

comision_dictamen_index:
  path: /dictamenes
  defaults: { _controller: App\Controller\ComisionController::misDictamenes }

comision_show_dictamen:
  path: /dictamen/{id}/show
  defaults: { _controller: App\Controller\ComisionController::showDictamen }

comision_show_proyecto:
  path: /proyecto/{id}/show
  defaults:
    { _controller: App\Controller\ComisionController::showProyectoComision }

comision_show_proyectosbae:
  path: /proyectosbae
  defaults:
    { _controller: App\Controller\ComisionController::indexProyectosBae }

comision_show_proyectobae:
  path: /proyectosbae/{id}/show
  defaults: { _controller: App\Controller\ComisionController::showProyectoBae }

giros_comisiones_index:
  path: /giros
  defaults: { _controller: App\Controller\ComisionController::indexGiros }

pedidos_informe_index:
  path: /pedidos
  defaults:
    { _controller: App\Controller\ComisionController::indexPedidoInforme }

digesto_informe_index:
  path: /digestos
  defaults:
    { _controller: App\Controller\ComisionController::indexInformesDigesto }

digesto_asignacion_index:
  path: /asignaciones
  defaults:
    { _controller: App\Controller\ComisionController::indexDictamenesOrd }

digesto_asignacion_show:
  path: /asignaciones/{id}/show
  defaults: { _controller: App\Controller\ComisionController::showAsignacion }

pedido_informe_proyectobae:
  path: /pedidos/{id}/show
  defaults: { _controller: App\Controller\ComisionController::showPedido }

digesto_informe_proyectobae:
  path: /digestos/{id}/show
  defaults: { _controller: App\Controller\ComisionController::showInforme }

giros_comision_imprimir:
  path: /giros/{id}/imprimir
  defaults: { _controller: App\Controller\ComisionController::imprimirGiros }

giros_asesor:
  path: /giros/asesor
  defaults:
    { _controller: App\Controller\ComisionController::expedientesAsesores }

show_asesor:
  path: /giros/asesor/{id}/show
  defaults: { _controller: App\Controller\ComisionController::showAsesor }
