dependencia_index:
    path:     /
    defaults: { _controller: App\Controller\DependenciaController::index }
    methods:  GET

dependencia_show:
    path:     /{id}/show
    defaults: { _controller: App\Controller\DependenciaController::show }
    methods:  GET

dependencia_new:
    path:     /new
    defaults: { _controller: App\Controller\DependenciaController::new }
    methods:  [GET, POST]

dependencia_edit:
    path:     /{id}/edit
    defaults: { _controller: App\Controller\DependenciaController::edit }
    methods:  [GET, POST]

dependencia_delete:
    path:     /{id}/delete
    defaults: { _controller: App\Controller\DependenciaController::delete }
    methods:  DELETE
