expediente_index:
  path: /
  defaults: { _controller: App\Controller\ExpedienteController::index }
  methods: GET

expediente_show:
  path: /{id}/show
  defaults: { _controller: App\Controller\ExpedienteController::show }
  methods: GET

expediente_new:
  path: /new
  defaults: { _controller: App\Controller\ExpedienteController::new }
  methods: [GET, POST]

expediente_edit:
  path: /{id}/edit
  defaults: { _controller: App\Controller\ExpedienteController::edit }
  methods: [GET, POST]

expediente_delete:
  path: /{id}/delete
  defaults: { _controller: App\Controller\ExpedienteController::delete }
  methods: DELETE

expediente_seguimiento:
  path: /seguimiento
  defaults:
    { _controller: App\Controller\ExpedienteController::seguimientoExpediente }

expediente_timeline:
  path: /{id}/timeline
  defaults:
    {
      _controller: App\Controller\ExpedienteController::seguimientoExpedienteTimeline,
    }

expediente_imprimir_caratula:
  path: /{id}/expediente_imprimir_caratula
  defaults:
    { _controller: App\Controller\ExpedienteController::imprimirCaratula }

expediente_imprimir_giro:
  path: /{id}/{giroId}/expediente_imprimir_giro/{tipoExpediente}
  defaults: { _controller: App\Controller\ExpedienteController::imprimirGiro }

expedientes_administrativos_index:
  path: /expedientes_administrativos_index
  defaults:
    {
      _controller: App\Controller\ExpedienteController::expedientesAdministrativosIndex,
    }

expedientes_administrativos_secretario_index:
  path: /expedientes_administrativos_secretario_index
  defaults:
    {
      _controller: App\Controller\ExpedienteController::expedientesAdministrativosSecretarioIndex,
    }

expedientes_administrativos_sector_index:
  path: /expedientes_administrativos_sector_index
  defaults:
    {
      _controller: App\Controller\ExpedienteController::expedientesAdministrativosSectorIndex,
    }

expedientes_administrativos_sector_recibidos:
  path: /expedientes_administrativos_sector_recibidos
  defaults:
    {
      _controller: App\Controller\ExpedienteController::expedientesAdministrativosRecibidosIndex,
    }

expedientes_administrativos_sector_enviados:
  path: /expedientes_administrativos_sector_enviados
  defaults:
    {
      _controller: App\Controller\ExpedienteController::expedientesAdministrativosEnviadosIndex,
    }

expediente_administrativo_sector_show:
  path: /expediente_administrativo_sector_show/{id}
  defaults:
    { _controller: App\Controller\ExpedienteController::showExpedienteRecibido }

expediente_sector_show:
  path: /expediente_sector_show/{id}
  defaults:
    { _controller: App\Controller\ExpedienteController::showExpedienteCreado }

imprimir_expediente_sector:
  path: /expediente_sector_imprimir/{id}
  defaults:
    {
      _controller: App\Controller\ExpedienteController::imprimirExpedienteSector,
    }

imprimir_proyecto_firmado:
  path: /expediente_firmado_imprimir/{id}
  defaults:
    {
      _controller: App\Controller\ExpedienteController::imprimirProyectoFirmado,
    }

imprimir_anexo_sector:
  path: /anexo_sector_imprimir/{id}
  defaults:
    { _controller: App\Controller\ExpedienteController::imprimirAnexoSector }

imprimir_anexo_giro:
  path: /anexo_giro_imprimir/{id}
  defaults:
    { _controller: App\Controller\ExpedienteController::imprimirAnexoGiro }

expediente_administrativo_sector_new:
  path: /expediente_administrativo_sector_new
  defaults:
    {
      _controller: App\Controller\ExpedienteController::nuevoExpedienteAdministrativoSector,
    }

bloqueo_delete:
  path: /expediente_bloqueados/{id}/delete
  defaults:
    { _controller: App\Controller\ExpedienteController::deleteBloqueado }

expedientes_bloqueados:
  path: /expediente_bloqueados
  defaults: { _controller: App\Controller\ExpedienteController::bloqueadoIndex }

expediente_administrativo_sector_rechazar:
  path: /expediente_administrativo_sector_rechazar/{id}
  defaults:
    {
      _controller: App\Controller\ExpedienteController::RechazarExpedienteSector,
    }

expediente_administrativo_sector_giro:
  path: /expediente_administrativo_sector_giro/{id}
  defaults:
    {
      _controller: App\Controller\ExpedienteController::nuevoGiroAdministrativoSector,
    }

expediente_bloqueado_index:
  path: /expediente_bloqueado_index
  defaults: { _controller: App\Controller\ExpedienteController::bloqueadoIndex }

expediente_bloqueado_delete:
  path: /expediente_bloqueado_delete/{id}
  defaults:
    {
      _controller: App\Controller\ExpedienteCController::deleteExpedienteBloqueado,
    }

#legislativos
expedientes_legislativos_index:
  path: /expedientes_legislativos_index
  defaults:
    {
      _controller: App\Controller\ExpedienteController::expedientesLegislativosIndex,
    }

proyectos_index:
  path: /proyectos
  defaults: { _controller: App\Controller\ExpedienteController::proyectosIndex }
  methods: GET

proyecto_show:
  path: /{id}/proyecto-ver
  defaults: { _controller: App\Controller\ExpedienteController::showProyecto }
  methods: [GET, POST]

proyecto_new:
  path: /proyecto-new
  defaults: { _controller: App\Controller\ExpedienteController::newProyecto }
  methods: [GET, POST]

proyecto_edit:
  path: /{id}/proyecto-edit
  defaults: { _controller: App\Controller\ExpedienteController::editProyecto }
  methods: [GET, POST]

expediente_imprimir_proyecto:
  path: /expediente_imprimir_proyecto/{id}
  defaults:
    { _controller: App\Controller\ExpedienteController::imprimirProyecto }

expediente_imprimir_proyecto_block:
  path: /expediente_imprimir_proyecto_block/{hash}
  defaults:
    { _controller: App\Controller\ExpedienteController::imprimirProyectoBlock }

expediente_impresion_proyecto:
  path: /expediente_impresion_proyecto
  defaults:
    { _controller: App\Controller\ExpedienteController::impresionProyecto }

expediente_asignar_numero:
  path: /expediente_asignar_numero
  defaults:
    {
      _controller: App\Controller\ExpedienteController::asignarNumeroExpediente,
    }

expediente_imprimir_etiqueta:
  path: /{id}/expediente_imprimir_etiqueta
  defaults:
    {
      _controller: App\Controller\ExpedienteController::expedienteImprimirEtiqueta,
    }

expediente_cargar_extracto:
  path: /{id}/expediente_cargar_extracto
  defaults: { _controller: App\Controller\ExpedienteController::cargarExtracto }

expediente_nuevo_giro_legislativo:
  path: /{id}/expediente-nuevo-giro-legislativo
  defaults: { _controller: App\Controller\ExpedienteController::nuevoGiro }

# administrativos
expediente_administrativo_nuevo:
  path: /expediente_administrativo_nuevo
  defaults:
    {
      _controller: App\Controller\ExpedienteController::nuevoExpedienteAdministrativo,
    }

expediente_administrativo_editar:
  path: /{id}/expediente_administrativo_editar
  defaults:
    {
      _controller: App\Controller\ExpedienteController::editarExpedienteAdministrativo,
    }

expediente_nuevo_giro_administrativo:
  path: /{id}/expediente-nuevo-giro-administrativo
  defaults:
    {
      _controller: App\Controller\ExpedienteController::nuevoGiroAdministrativo,
    }

#legislativos externos
expediente_legislativo_externo_index:
  path: /expediente_legislativo_externo_index
  defaults:
    {
      _controller: App\Controller\ExpedienteController::expedientesLegislativoExternosIndex,
    }

expediente_legislativo_externo_nuevo:
  path: /expediente_legislativo_externo_nuevo
  defaults:
    {
      _controller: App\Controller\ExpedienteController::nuevoExpedienteLegislativoExterno,
    }

expediente_legislativo_externo_editar:
  path: /{id}/expediente_legislativo_externo_editar
  defaults:
    {
      _controller: App\Controller\ExpedienteController::editarExpedienteLegislativoExterno,
    }

expediente_legislativo_externo_giro:
  path: /{id}/expediente-legislativo-externo-giro
  defaults:
    { _controller: App\Controller\ExpedienteController::asignarGiroComision }

#administrativos externos
expediente_administrativo_externo_index:
  path: /expediente_administrativo_externo_index
  defaults:
    {
      _controller: App\Controller\ExpedienteController::expedientesAdministrativoExternosIndex,
    }

expediente_administrativo_externo_nuevo:
  path: /expediente_administrativo_externo_nuevo
  defaults:
    {
      _controller: App\Controller\ExpedienteController::nuevoExpedienteAdministrativoExterno,
    }

expediente_administrativo_externo_editar:
  path: /{id}/expediente_administrativo_externo_editar
  defaults:
    {
      _controller: App\Controller\ExpedienteController::editarExpedienteAdministrativoExterno,
    }

expediente_editar_extracto:
  path: /{id}/editarExtracto
  defaults: { _controller: App\Controller\ExpedienteController::editarExtracto }
  methods: [GET, POST]

expediente_show_edicion_extracto:
  path: /{expediente}/editarExtracto/{logExpediente}
  defaults:
    { _controller: App\Controller\ExpedienteController::showEdicionExtracto }
  methods: [GET]

#Expedientes en sesion

incorporar_expedientes_a_sesion_index:
  path: /incorporar_expedientes_a_sesion_index
  defaults:
    {
      _controller: App\Controller\ExpedienteController::incorporarProyectosASesionIndex,
    }
