easy_admin:
    entities:
        Persona:
            class: App\Entity\Persona
            form:
                fields:
                    - { property: 'nombre' }
                    - { property: 'apellido' }
                    - { property: 'dni' }
                    - { property: 'fechaNacimiento' }
                    - { property: 'domicilioPersona' , type: 'collection' , type_options: { by_reference: false, entry_type: App\Form\DomicilioPersonaType } }
                    - { property: 'cargoPersona' , type: 'collection' , type_options: { by_reference: false, allow_delete: true, entry_type: App\Form\CargoPersonaType } }