easy_admin:
    entities:
        Sesion:
            class: App\Entity\Sesion
            form:
                fields:
                    - { property: 'titulo' }
                    - { property: 'numeroReunion' }
                    - { property: 'fecha', type_options: { widget: 'single_text', html5: true } }
                    - { property: 'tipoSesion', type: 'entity', type_options: { 'query_builder': ['App\Repository\ParametroRepository', 'findTipoSesionActivo'] } }
                    - { property: 'ordenDelDia', type: 'fos_ckeditor'}
                    - { property: 'asuntosEntrados', type: 'fos_ckeditor'}
                    - { property: 'acta', type: 'fos_ckeditor'}
            show:
                title:  'Ver Sesi贸n'
                fields:
                    - { property: 'titulo' }
                    - { property: 'fecha' }
                    - { property: 'tipoSesion' }
                    - { property: 'ordenDelDia' }
                    - { property: 'asuntosEntrados' }
                    - { property: 'acta', type: 'raw' }
            edit:
                title:  'Editar Sesi贸n'
            new:
                title:  'Alta Sesi贸n'
            list:
                title:  'Sesi贸n'