services:
    mailer.dev.set_recipients:
        class: Symfony\Component\Mailer\EventListener\EnvelopeListener
        tags: ['kernel.event_subscriber']
        arguments:
            $sender: '%env(EMAIL_FROM)%'
            $recipients: ['matias.delatorre89@gmail.com']
