app_homepage:
  path:     /
  defaults: { _controller: App\Controller\DefaultController::index }

app_proyectobae:
  resource: "routing/proyectobae.yml"
  prefix:   /proyectobae

app_dictamenes:
  resource: "routing/dictamen.yml"
  prefix:   /dictamen

app_dependencia:
  resource: "routing/dependencia.yml"
  prefix:   /dependencia

app_persona:
  resource: "routing/persona.yml"
  prefix:   /persona

app_ajax:
  resource: "routing/ajax.yml"
  prefix:   /ajax

app_mocion:
  resource: "routing/mocion.yml"
  prefix:   /sesion/mocion

app_tipomayoria:
  resource: "routing/tipomayoria.yml"
  prefix:   /tipomayoria

app_concejal:
  path:     /concejal
  defaults: { _controller: App\Controller\DefaultController::concejal }

documento_carta_organica:
  path:     /documento_carta_organica
  defaults: { _controller: App\Controller\DefaultController::cartaOrganica }

get_concejales_admin:
  path: /concejales
  defaults: { _controller: App\Controller\AjaxController::getConcejales }

sesiones:
  resource: "routing/sesiones.yml"
  prefix: /interno-sesiones

app_decreto:
  resource: "routing/decreto.yml"
  prefix:   /decreto

#app_display:
#    path:     /display
#    defaults: { _controller: AppBundle:Default:display }

#app_votar:
#    path:     /votar
#    defaults: { _controller: AppBundle:Mocion:votoConcejal }
#    methods:  POST

app_orden_de_pago:
  resource: "routing/ordendepago.yml"
  prefix:   /orden-de-pago

