<?php

namespace MesaEntradaBundle\Repository;

/**
 * DictamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictamenRepository extends \Doctrine\ORM\EntityRepository {

	public function getQbAll() {
		return $this->createQueryBuilder( 'd' );

	}
}
