<?php

namespace MesaEntradaBundle\Repository;

/**
 * DictamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictamenRepository extends \Doctrine\ORM\EntityRepository
{

    public function getQbAll()
    {
        return $this->createQueryBuilder('d');

    }

    public function getQbBuscar($data)
    {
        $qb = $this->getQbAll();

        if (isset($data['expediente'])) {
            $q = $data['expediente'];
            $qb->join('d.expediente', 'expediente');
            $qb->andWhere('UPPER(expediente.expediente) LIKE UPPER(:expediente)')
                ->setParameter('expediente', "%$q%");
        }

        return $qb;
    }
}
