<?php

namespace MesaEntradaBundle\Repository;

/**
 * GiroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiroAdministrativoRepository extends \Doctrine\ORM\EntityRepository
{
}
