<?php

namespace MesaEntradaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IniciadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IniciadorRepository extends EntityRepository {
	public function getCargosPorNombre( $apellido, $limit = 10, $returnArray = false ) {
		$qb = $this->createQueryBuilder( 'i' )
		           ->addSelect( 'p' )
		           ->addSelect( 'c' )
		           ->addSelect( 'cp' );
		$qb
			->join( 'i.persona', 'p' )
			->join( 'p.cargoPersona', 'cp' )
			->join( 'cp.cargo', 'c' )
			->where( "upper(p.apellido) like upper(:apellido)" );
		$qb->setParameter( 'apellido', '%' . $apellido . '%' );

		$qb->setMaxResults( $limit );

		if ( $returnArray ) {
			return $qb->getQuery()->getArrayResult();
		} else {
			return $qb->getQuery()->getResult();
		}
	}
}
