<?php

namespace MesaEntradaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IniciadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IniciadorRepository extends EntityRepository
{
}
