<?php

namespace MesaEntradaBundle\Repository;

/**
 * TextoDefinitivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextoDefinitivoRepository extends \Doctrine\ORM\EntityRepository
{
}
