<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20221202123450 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('ALTER TABLE beneficiario_norma DROP CONSTRAINT fk_b43f3af44b64abc7');
        $this->addSql('ALTER TABLE norma DROP CONSTRAINT fk_3ef6217e934d3676');
        $this->addSql('ALTER TABLE palabra_clave_norma DROP CONSTRAINT fk_58f066a97e0cd09e');
        $this->addSql('ALTER TABLE descriptor_norma DROP CONSTRAINT fk_9a9beef02a13d45');
        $this->addSql('ALTER TABLE identificador_norma DROP CONSTRAINT fk_29c6dd41bfd0b734');
        $this->addSql('ALTER TABLE cambio_anexo DROP CONSTRAINT fk_a7117202e06fc29e');
        $this->addSql('ALTER TABLE caducidad DROP CONSTRAINT fk_5aebd421e06fc29e');
        $this->addSql('ALTER TABLE adhesiones DROP CONSTRAINT fk_efbedb94e06fc29e');
        $this->addSql('ALTER TABLE anexo_original_norma DROP CONSTRAINT fk_7695817fe06fc29e');
        $this->addSql('ALTER TABLE abrogacion DROP CONSTRAINT fk_abe8f69163d6954a');
        $this->addSql('ALTER TABLE abrogacion DROP CONSTRAINT fk_abe8f691e06fc29e');
        $this->addSql('ALTER TABLE articulo_suprimido DROP CONSTRAINT fk_50f5bdafe06fc29e');
        $this->addSql('ALTER TABLE estado_norma DROP CONSTRAINT fk_340da78ce06fc29e');
        $this->addSql('ALTER TABLE norma_consolidacion DROP CONSTRAINT fk_c3caedc8e06fc29e');
        $this->addSql('ALTER TABLE cambio_norma DROP CONSTRAINT fk_5499fc50e06fc29e');
        $this->addSql('ALTER TABLE palabra_clave_norma DROP CONSTRAINT fk_58f066a9e06fc29e');
        $this->addSql('ALTER TABLE conflicto_normativo DROP CONSTRAINT fk_90e7d3f0c60326cb');
        $this->addSql('ALTER TABLE conflicto_normativo DROP CONSTRAINT fk_90e7d3f0e06fc29e');
        $this->addSql('ALTER TABLE descriptor_norma DROP CONSTRAINT fk_9a9beef0e06fc29e');
        $this->addSql('ALTER TABLE observacion_antecedente DROP CONSTRAINT fk_9ed78a29e06fc29e');
        $this->addSql('ALTER TABLE fundamentacion DROP CONSTRAINT fk_e1813ae6e06fc29e');
        $this->addSql('ALTER TABLE tema_norma DROP CONSTRAINT fk_69ff1705e06fc29e');
        $this->addSql('ALTER TABLE refundicion DROP CONSTRAINT fk_cbfa0e8d99305259');
        $this->addSql('ALTER TABLE refundicion DROP CONSTRAINT fk_cbfa0e8de06fc29e');
        $this->addSql('ALTER TABLE anexo_norma DROP CONSTRAINT fk_2440d254e06fc29e');
        $this->addSql('ALTER TABLE identificador_norma DROP CONSTRAINT fk_29c6dd41e06fc29e');
        $this->addSql('ALTER TABLE beneficiario_norma DROP CONSTRAINT fk_b43f3af4e06fc29e');
        $this->addSql('ALTER TABLE anexo_consolidacion DROP CONSTRAINT fk_29c9d32c56f6e268');
        $this->addSql('ALTER TABLE cambio_anexo DROP CONSTRAINT fk_a711720256f6e268');
        $this->addSql('ALTER TABLE caducidad DROP CONSTRAINT fk_5aebd42156f6e268');
        $this->addSql('ALTER TABLE abrogacion DROP CONSTRAINT fk_abe8f69156f6e268');
        $this->addSql('ALTER TABLE articulo_suprimido DROP CONSTRAINT fk_50f5bdaf56f6e268');
        $this->addSql('ALTER TABLE estado_norma DROP CONSTRAINT fk_340da78c56f6e268');
        $this->addSql('ALTER TABLE norma_consolidacion DROP CONSTRAINT fk_c3caedc856f6e268');
        $this->addSql('ALTER TABLE cambio_norma DROP CONSTRAINT fk_5499fc5056f6e268');
        $this->addSql('ALTER TABLE conflicto_normativo DROP CONSTRAINT fk_90e7d3f056f6e268');
        $this->addSql('ALTER TABLE observacion_antecedente DROP CONSTRAINT fk_9ed78a2956f6e268');
        $this->addSql('ALTER TABLE fundamentacion DROP CONSTRAINT fk_e1813ae656f6e268');
        $this->addSql('ALTER TABLE refundicion DROP CONSTRAINT fk_cbfa0e8d56f6e268');
        $this->addSql('ALTER TABLE identificador DROP CONSTRAINT fk_a82558811a0c582f');
        $this->addSql('ALTER TABLE norma DROP CONSTRAINT fk_3ef6217e3c66e029');
        $this->addSql('ALTER TABLE norma DROP CONSTRAINT fk_3ef6217e89500f1d');
        $this->addSql('ALTER TABLE norma DROP CONSTRAINT fk_3ef6217eaf03385e');
        $this->addSql('ALTER TABLE adhesiones DROP CONSTRAINT fk_efbedb9453347b49');
        $this->addSql('ALTER TABLE caducidad DROP CONSTRAINT fk_5aebd4213e118c56');
        $this->addSql('ALTER TABLE tema_norma DROP CONSTRAINT fk_69ff1705a64a8a17');
        $this->addSql('ALTER TABLE tema DROP CONSTRAINT fk_61e3a538c958426f');
        $this->addSql('ALTER TABLE web_digesto_documento_anexo DROP CONSTRAINT fk_a641aa86d3897d4b');
        $this->addSql('ALTER TABLE estado_norma DROP CONSTRAINT fk_340da78c9f5a440b');
        $this->addSql('ALTER TABLE norma DROP CONSTRAINT fk_3ef6217e3f799e6a');
        $this->addSql('DROP SEQUENCE abrogacion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE adhesiones_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE anexo_consolidacion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE anexo_norma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE anexo_original_norma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE articulo_suprimido_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE beneficiario_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE beneficiario_norma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE boletin_oficial_municipal_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE caducidad_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE cambio_anexo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE cambio_norma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE conflicto_normativo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE consolidacion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE descriptor_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE descriptor_norma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE estado_norma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ext_log_entries_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE fundamentacion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE identificador_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE identificador_norma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE norma_consolidacion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE norma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE observacion_antecedente_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE palabra_clave_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE palabra_clave_norma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE refundicion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tema_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tema_norma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tipo_boletin_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tipo_caducidad_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tipo_estado_norma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tipo_identificador_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tipo_norma_adhesion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tipo_ordenanza_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tipo_promulgacion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tipo_veto_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE web_digesto_documento_anexo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE web_digesto_documento_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE web_digesto_texto_id_seq CASCADE');
        $this->addSql('CREATE SEQUENCE paciente_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE orden_medica_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE paciente (id INT NOT NULL, persona_id INT NOT NULL, grupo VARCHAR(10) DEFAULT NULL, factor VARCHAR(10) NOT NULL, observaciones TEXT DEFAULT NULL, foto VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C6CBA95EF5F88DB9 ON paciente (persona_id)');
        $this->addSql('CREATE TABLE orden_medica (id INT NOT NULL, paciente_id INT NOT NULL, articulo_id INT NOT NULL, medico_otorgante VARCHAR(255) NOT NULL, desde DATE NOT NULL, hasta DATE NOT NULL, diagnostico VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3BC688FA7310DAD4 ON orden_medica (paciente_id)');
        $this->addSql('CREATE INDEX IDX_3BC688FA2DBC2FC9 ON orden_medica (articulo_id)');
        $this->addSql('ALTER TABLE paciente ADD CONSTRAINT FK_C6CBA95EF5F88DB9 FOREIGN KEY (persona_id) REFERENCES persona (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orden_medica ADD CONSTRAINT FK_3BC688FA7310DAD4 FOREIGN KEY (paciente_id) REFERENCES paciente (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orden_medica ADD CONSTRAINT FK_3BC688FA2DBC2FC9 FOREIGN KEY (articulo_id) REFERENCES personal_articulo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE beneficiario');
        $this->addSql('DROP TABLE boletin_oficial_municipal');
        $this->addSql('DROP TABLE anexo_consolidacion');
        $this->addSql('DROP TABLE cambio_anexo');
        $this->addSql('DROP TABLE caducidad');
        $this->addSql('DROP TABLE adhesiones');
        $this->addSql('DROP TABLE anexo_original_norma');
        $this->addSql('DROP TABLE abrogacion');
        $this->addSql('DROP TABLE articulo_suprimido');
        $this->addSql('DROP TABLE palabra_clave');
        $this->addSql('DROP TABLE descriptor');
        $this->addSql('DROP TABLE estado_norma');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE identificador');
        $this->addSql('DROP TABLE norma_consolidacion');
        $this->addSql('DROP TABLE norma');
        $this->addSql('DROP TABLE consolidacion');
        $this->addSql('DROP TABLE cambio_norma');
        $this->addSql('DROP TABLE palabra_clave_norma');
        $this->addSql('DROP TABLE conflicto_normativo');
        $this->addSql('DROP TABLE descriptor_norma');
        $this->addSql('DROP TABLE observacion_antecedente');
        $this->addSql('DROP TABLE fundamentacion');
        $this->addSql('DROP TABLE tema_norma');
        $this->addSql('DROP TABLE tipo_identificador');
        $this->addSql('DROP TABLE refundicion');
        $this->addSql('DROP TABLE tipo_boletin');
        $this->addSql('DROP TABLE tipo_ordenanza');
        $this->addSql('DROP TABLE tipo_veto');
        $this->addSql('DROP TABLE tipo_norma_adhesion');
        $this->addSql('DROP TABLE tipo_caducidad');
        $this->addSql('DROP TABLE tema');
        $this->addSql('DROP TABLE web_digesto_documento');
        $this->addSql('DROP TABLE web_digesto_documento_anexo');
        $this->addSql('DROP TABLE web_digesto_texto');
        $this->addSql('DROP TABLE anexo_norma');
        $this->addSql('DROP TABLE identificador_norma');
        $this->addSql('DROP TABLE tipo_estado_norma');
        $this->addSql('DROP TABLE tipo_promulgacion');
        $this->addSql('DROP TABLE beneficiario_norma');
        $this->addSql('ALTER TABLE expediente ADD marca_temporal VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE expediente ADD hash VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE expediente ADD marca_definitivo BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE area_administrativa DROP CONSTRAINT fk_25706caddf2432b6');
        $this->addSql('DROP INDEX uniq_25706caddf2432b6');
        $this->addSql('ALTER TABLE area_administrativa DROP dependencia_id');
        $this->addSql('ALTER TABLE personal_articulo ADD dias INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fos_user DROP CONSTRAINT fk_957a6479bd0f409c');
        $this->addSql('DROP INDEX idx_957a6479bd0f409c');
        $this->addSql('ALTER TABLE fos_user DROP area_id');
        $this->addSql('ALTER TABLE fos_user ALTER roles TYPE JSON');
        $this->addSql('ALTER TABLE fos_user ALTER roles DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN fos_user.roles IS NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE orden_medica DROP CONSTRAINT FK_3BC688FA7310DAD4');
        $this->addSql('DROP SEQUENCE paciente_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE orden_medica_id_seq CASCADE');
        $this->addSql('CREATE SEQUENCE abrogacion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE adhesiones_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE anexo_consolidacion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE anexo_norma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE anexo_original_norma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE articulo_suprimido_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE beneficiario_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE beneficiario_norma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE boletin_oficial_municipal_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE caducidad_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE cambio_anexo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE cambio_norma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE conflicto_normativo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE consolidacion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE descriptor_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE descriptor_norma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE estado_norma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ext_log_entries_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE fundamentacion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE identificador_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE identificador_norma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE norma_consolidacion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE norma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE observacion_antecedente_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE palabra_clave_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE palabra_clave_norma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE refundicion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tema_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tema_norma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tipo_boletin_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tipo_caducidad_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tipo_estado_norma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tipo_identificador_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tipo_norma_adhesion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tipo_ordenanza_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tipo_promulgacion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tipo_veto_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE web_digesto_documento_anexo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE web_digesto_documento_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE web_digesto_texto_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE beneficiario (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, apellido VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_e8d0b617f6167a1c ON beneficiario (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_e8d0b617fe35d8c4 ON beneficiario (creado_por_id)');
        $this->addSql('CREATE TABLE boletin_oficial_municipal (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, numero INT NOT NULL, fecha_publicacion DATE NOT NULL, paginas INT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, nombre_documento VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_4d4d4fd4fe35d8c4 ON boletin_oficial_municipal (creado_por_id)');
        $this->addSql('CREATE INDEX idx_4d4d4fd4f6167a1c ON boletin_oficial_municipal (actualizado_por_id)');
        $this->addSql('CREATE TABLE anexo_consolidacion (id INT NOT NULL, consolidacion_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, titulo VARCHAR(255) NOT NULL, descripcion VARCHAR(255) DEFAULT NULL, nombre_archivo VARCHAR(255) DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, orden INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_29c9d32c56f6e268 ON anexo_consolidacion (consolidacion_id)');
        $this->addSql('CREATE INDEX idx_29c9d32cfe35d8c4 ON anexo_consolidacion (creado_por_id)');
        $this->addSql('CREATE INDEX idx_29c9d32cf6167a1c ON anexo_consolidacion (actualizado_por_id)');
        $this->addSql('CREATE TABLE cambio_anexo (id INT NOT NULL, consolidacion_id INT NOT NULL, norma_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, fecha DATE NOT NULL, anexo VARCHAR(255) NOT NULL, descripcion TEXT NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_a7117202fe35d8c4 ON cambio_anexo (creado_por_id)');
        $this->addSql('CREATE INDEX idx_a7117202f6167a1c ON cambio_anexo (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_a711720256f6e268 ON cambio_anexo (consolidacion_id)');
        $this->addSql('CREATE INDEX idx_a7117202e06fc29e ON cambio_anexo (norma_id)');
        $this->addSql('CREATE TABLE caducidad (id INT NOT NULL, norma_id INT NOT NULL, consolidacion_id INT NOT NULL, tipo_caducidad_id INT DEFAULT NULL, norma_completa BOOLEAN NOT NULL, articulo VARCHAR(255) DEFAULT NULL, articulo_anexo VARCHAR(255) DEFAULT NULL, fundamentacion TEXT NOT NULL, observaciones TEXT DEFAULT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_5aebd4213e118c56 ON caducidad (tipo_caducidad_id)');
        $this->addSql('CREATE INDEX idx_5aebd421f6167a1c ON caducidad (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_5aebd42156f6e268 ON caducidad (consolidacion_id)');
        $this->addSql('CREATE INDEX idx_5aebd421fe35d8c4 ON caducidad (creado_por_id)');
        $this->addSql('CREATE INDEX idx_5aebd421e06fc29e ON caducidad (norma_id)');
        $this->addSql('CREATE TABLE adhesiones (id INT NOT NULL, norma_id INT DEFAULT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, tipo_norma_adhesion_id INT DEFAULT NULL, adhesion VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_efbedb9453347b49 ON adhesiones (tipo_norma_adhesion_id)');
        $this->addSql('CREATE INDEX idx_efbedb94e06fc29e ON adhesiones (norma_id)');
        $this->addSql('CREATE INDEX idx_efbedb94fe35d8c4 ON adhesiones (creado_por_id)');
        $this->addSql('CREATE INDEX idx_efbedb94f6167a1c ON adhesiones (actualizado_por_id)');
        $this->addSql('CREATE TABLE anexo_original_norma (id INT NOT NULL, norma_id INT DEFAULT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, titulo VARCHAR(255) DEFAULT NULL, fecha DATE DEFAULT NULL, archivo VARCHAR(255) NOT NULL, orden INT NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_7695817ff6167a1c ON anexo_original_norma (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_7695817ffe35d8c4 ON anexo_original_norma (creado_por_id)');
        $this->addSql('CREATE INDEX idx_7695817fe06fc29e ON anexo_original_norma (norma_id)');
        $this->addSql('CREATE TABLE abrogacion (id INT NOT NULL, norma_id INT NOT NULL, norma_abrogante_id INT NOT NULL, consolidacion_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, norma_completa BOOLEAN NOT NULL, articulo VARCHAR(255) DEFAULT NULL, articulo_anexo VARCHAR(255) DEFAULT NULL, articulo_abrogante VARCHAR(255) DEFAULT NULL, anexo_abrogante VARCHAR(255) DEFAULT NULL, fundamentacion TEXT NOT NULL, observaciones TEXT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_abe8f691f6167a1c ON abrogacion (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_abe8f691fe35d8c4 ON abrogacion (creado_por_id)');
        $this->addSql('CREATE INDEX idx_abe8f691e06fc29e ON abrogacion (norma_id)');
        $this->addSql('CREATE INDEX idx_abe8f69156f6e268 ON abrogacion (consolidacion_id)');
        $this->addSql('CREATE INDEX idx_abe8f69163d6954a ON abrogacion (norma_abrogante_id)');
        $this->addSql('CREATE TABLE articulo_suprimido (id INT NOT NULL, consolidacion_id INT NOT NULL, norma_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, fecha DATE NOT NULL, articulo VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_50f5bdafe06fc29e ON articulo_suprimido (norma_id)');
        $this->addSql('CREATE INDEX idx_50f5bdaffe35d8c4 ON articulo_suprimido (creado_por_id)');
        $this->addSql('CREATE INDEX idx_50f5bdaff6167a1c ON articulo_suprimido (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_50f5bdaf56f6e268 ON articulo_suprimido (consolidacion_id)');
        $this->addSql('CREATE TABLE palabra_clave (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_8caf1cfafe35d8c4 ON palabra_clave (creado_por_id)');
        $this->addSql('CREATE INDEX idx_8caf1cfaf6167a1c ON palabra_clave (actualizado_por_id)');
        $this->addSql('CREATE TABLE descriptor (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_3927602fe35d8c4 ON descriptor (creado_por_id)');
        $this->addSql('CREATE INDEX idx_3927602f6167a1c ON descriptor (actualizado_por_id)');
        $this->addSql('CREATE TABLE estado_norma (id INT NOT NULL, norma_id INT NOT NULL, consolidacion_id INT NOT NULL, estado_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_340da78ce06fc29e ON estado_norma (norma_id)');
        $this->addSql('CREATE INDEX idx_340da78cfe35d8c4 ON estado_norma (creado_por_id)');
        $this->addSql('CREATE INDEX idx_340da78c9f5a440b ON estado_norma (estado_id)');
        $this->addSql('CREATE INDEX idx_340da78cf6167a1c ON estado_norma (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_340da78c56f6e268 ON estado_norma (consolidacion_id)');
        $this->addSql('CREATE TABLE ext_log_entries (id INT NOT NULL, action VARCHAR(8) NOT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data TEXT DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX log_version_lookup_idx ON ext_log_entries (object_id, object_class, version)');
        $this->addSql('CREATE INDEX log_date_lookup_idx ON ext_log_entries (logged_at)');
        $this->addSql('CREATE INDEX log_class_lookup_idx ON ext_log_entries (object_class)');
        $this->addSql('CREATE INDEX log_user_lookup_idx ON ext_log_entries (username)');
        $this->addSql('COMMENT ON COLUMN ext_log_entries.data IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE identificador (id INT NOT NULL, tipo_identificador_id INT DEFAULT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_a82558811a0c582f ON identificador (tipo_identificador_id)');
        $this->addSql('CREATE INDEX idx_a8255881f6167a1c ON identificador (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_a8255881fe35d8c4 ON identificador (creado_por_id)');
        $this->addSql('CREATE TABLE norma_consolidacion (id INT NOT NULL, norma_id INT NOT NULL, consolidacion_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_c3caedc8f6167a1c ON norma_consolidacion (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_c3caedc856f6e268 ON norma_consolidacion (consolidacion_id)');
        $this->addSql('CREATE INDEX idx_c3caedc8fe35d8c4 ON norma_consolidacion (creado_por_id)');
        $this->addSql('CREATE INDEX idx_c3caedc8e06fc29e ON norma_consolidacion (norma_id)');
        $this->addSql('CREATE TABLE norma (id INT NOT NULL, tipo_promulgacion_id INT DEFAULT NULL, rama_id INT DEFAULT NULL, rama_vigente_no_consolidada_id INT DEFAULT NULL, tipo_boletin_id INT DEFAULT NULL, tipo_ordenanza_id INT DEFAULT NULL, boletin_oficial_municipal_id INT DEFAULT NULL, tipo_veto_id INT DEFAULT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, fecha_sancion DATE DEFAULT NULL, tema_general VARCHAR(2048) NOT NULL, numero INT NOT NULL, pagina_boletin INT DEFAULT NULL, observacion TEXT DEFAULT NULL, decreto_promulgatorio VARCHAR(255) DEFAULT NULL, fecha_promulgacion DATE DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, numero_anterior INT DEFAULT NULL, texto TEXT DEFAULT NULL, vigente_no_consolidada BOOLEAN DEFAULT NULL, nombre_archivo VARCHAR(255) DEFAULT NULL, numero_boletin INT DEFAULT NULL, fecha_publicacion_boletin DATE DEFAULT NULL, observaciones_veto TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_3ef6217eaf03385e ON norma (tipo_veto_id)');
        $this->addSql('CREATE INDEX idx_3ef6217e89500f1d ON norma (tipo_ordenanza_id)');
        $this->addSql('CREATE INDEX idx_3ef6217e3c66e029 ON norma (tipo_boletin_id)');
        $this->addSql('CREATE INDEX idx_3ef6217e82f348f1 ON norma (rama_vigente_no_consolidada_id)');
        $this->addSql('CREATE INDEX idx_3ef6217e3f799e6a ON norma (tipo_promulgacion_id)');
        $this->addSql('CREATE INDEX idx_3ef6217e934d3676 ON norma (boletin_oficial_municipal_id)');
        $this->addSql('CREATE INDEX idx_3ef6217ef6167a1c ON norma (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_3ef6217e5e0bfd3b ON norma (rama_id)');
        $this->addSql('CREATE INDEX idx_3ef6217efe35d8c4 ON norma (creado_por_id)');
        $this->addSql('CREATE TABLE consolidacion (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, anio INT NOT NULL, fecha DATE NOT NULL, titulo VARCHAR(255) DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, url VARCHAR(255) DEFAULT NULL, nombre_archivo_proyecto VARCHAR(255) DEFAULT NULL, en_curso BOOLEAN DEFAULT \'false\' NOT NULL, visible BOOLEAN DEFAULT \'false\' NOT NULL, ultima BOOLEAN DEFAULT \'false\' NOT NULL, publicada_en_el_boletin BOOLEAN DEFAULT \'false\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_f22af2bdfe35d8c4 ON consolidacion (creado_por_id)');
        $this->addSql('CREATE INDEX idx_f22af2bdf6167a1c ON consolidacion (actualizado_por_id)');
        $this->addSql('CREATE TABLE cambio_norma (id INT NOT NULL, norma_id INT DEFAULT NULL, consolidacion_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, fecha DATE NOT NULL, articulo VARCHAR(255) NOT NULL, fuente VARCHAR(2048) DEFAULT NULL, remision_externa TEXT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_5499fc50fe35d8c4 ON cambio_norma (creado_por_id)');
        $this->addSql('CREATE INDEX idx_5499fc50f6167a1c ON cambio_norma (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_5499fc50e06fc29e ON cambio_norma (norma_id)');
        $this->addSql('CREATE INDEX idx_5499fc5056f6e268 ON cambio_norma (consolidacion_id)');
        $this->addSql('CREATE TABLE palabra_clave_norma (id INT NOT NULL, norma_id INT NOT NULL, palabra_clave_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_58f066a9f6167a1c ON palabra_clave_norma (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_58f066a9fe35d8c4 ON palabra_clave_norma (creado_por_id)');
        $this->addSql('CREATE INDEX idx_58f066a9e06fc29e ON palabra_clave_norma (norma_id)');
        $this->addSql('CREATE INDEX idx_58f066a97e0cd09e ON palabra_clave_norma (palabra_clave_id)');
        $this->addSql('CREATE TABLE conflicto_normativo (id INT NOT NULL, norma_id INT NOT NULL, conflicto_con_norma_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, consolidacion_id INT NOT NULL, articulo VARCHAR(255) DEFAULT NULL, articulo_anexo VARCHAR(255) DEFAULT NULL, articulo_conflicto VARCHAR(255) DEFAULT NULL, articulo_anexo_conflicto VARCHAR(255) DEFAULT NULL, fundamentacion TEXT NOT NULL, observaciones TEXT DEFAULT NULL, norma_completa BOOLEAN NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_90e7d3f056f6e268 ON conflicto_normativo (consolidacion_id)');
        $this->addSql('CREATE INDEX idx_90e7d3f0c60326cb ON conflicto_normativo (conflicto_con_norma_id)');
        $this->addSql('CREATE INDEX idx_90e7d3f0fe35d8c4 ON conflicto_normativo (creado_por_id)');
        $this->addSql('CREATE INDEX idx_90e7d3f0f6167a1c ON conflicto_normativo (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_90e7d3f0e06fc29e ON conflicto_normativo (norma_id)');
        $this->addSql('CREATE TABLE descriptor_norma (id INT NOT NULL, norma_id INT NOT NULL, descriptor_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_9a9beef0e06fc29e ON descriptor_norma (norma_id)');
        $this->addSql('CREATE INDEX idx_9a9beef0f6167a1c ON descriptor_norma (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_9a9beef02a13d45 ON descriptor_norma (descriptor_id)');
        $this->addSql('CREATE INDEX idx_9a9beef0fe35d8c4 ON descriptor_norma (creado_por_id)');
        $this->addSql('CREATE TABLE observacion_antecedente (id INT NOT NULL, consolidacion_id INT NOT NULL, norma_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, observaciones TEXT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_9ed78a2956f6e268 ON observacion_antecedente (consolidacion_id)');
        $this->addSql('CREATE INDEX idx_9ed78a29e06fc29e ON observacion_antecedente (norma_id)');
        $this->addSql('CREATE INDEX idx_9ed78a29f6167a1c ON observacion_antecedente (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_9ed78a29fe35d8c4 ON observacion_antecedente (creado_por_id)');
        $this->addSql('CREATE TABLE fundamentacion (id INT NOT NULL, consolidacion_id INT NOT NULL, norma_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, fundamentacion TEXT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_e1813ae6fe35d8c4 ON fundamentacion (creado_por_id)');
        $this->addSql('CREATE INDEX idx_e1813ae6e06fc29e ON fundamentacion (norma_id)');
        $this->addSql('CREATE INDEX idx_e1813ae6f6167a1c ON fundamentacion (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_e1813ae656f6e268 ON fundamentacion (consolidacion_id)');
        $this->addSql('CREATE TABLE tema_norma (id INT NOT NULL, tema_id INT NOT NULL, norma_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_69ff1705a64a8a17 ON tema_norma (tema_id)');
        $this->addSql('CREATE INDEX idx_69ff1705f6167a1c ON tema_norma (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_69ff1705e06fc29e ON tema_norma (norma_id)');
        $this->addSql('CREATE INDEX idx_69ff1705fe35d8c4 ON tema_norma (creado_por_id)');
        $this->addSql('CREATE TABLE tipo_identificador (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_a8960bdffe35d8c4 ON tipo_identificador (creado_por_id)');
        $this->addSql('CREATE INDEX idx_a8960bdff6167a1c ON tipo_identificador (actualizado_por_id)');
        $this->addSql('CREATE TABLE refundicion (id INT NOT NULL, norma_id INT NOT NULL, norma_refundida_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, consolidacion_id INT NOT NULL, articulo VARCHAR(255) DEFAULT NULL, articulo_anexo VARCHAR(255) DEFAULT NULL, norma_completa BOOLEAN NOT NULL, articulo_refundido VARCHAR(255) DEFAULT NULL, articulo_anexo_refundido VARCHAR(255) DEFAULT NULL, fundamentacion TEXT NOT NULL, observaciones TEXT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_cbfa0e8d56f6e268 ON refundicion (consolidacion_id)');
        $this->addSql('CREATE INDEX idx_cbfa0e8dfe35d8c4 ON refundicion (creado_por_id)');
        $this->addSql('CREATE INDEX idx_cbfa0e8df6167a1c ON refundicion (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_cbfa0e8de06fc29e ON refundicion (norma_id)');
        $this->addSql('CREATE INDEX idx_cbfa0e8d99305259 ON refundicion (norma_refundida_id)');
        $this->addSql('CREATE TABLE tipo_boletin (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_76e9dfddf6167a1c ON tipo_boletin (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_76e9dfddfe35d8c4 ON tipo_boletin (creado_por_id)');
        $this->addSql('CREATE TABLE tipo_ordenanza (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_46bcfab5fe35d8c4 ON tipo_ordenanza (creado_por_id)');
        $this->addSql('CREATE INDEX idx_46bcfab5f6167a1c ON tipo_ordenanza (actualizado_por_id)');
        $this->addSql('CREATE TABLE tipo_veto (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_bd7d3ee9f6167a1c ON tipo_veto (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_bd7d3ee9fe35d8c4 ON tipo_veto (creado_por_id)');
        $this->addSql('CREATE TABLE tipo_norma_adhesion (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_537c3f2bf6167a1c ON tipo_norma_adhesion (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_537c3f2bfe35d8c4 ON tipo_norma_adhesion (creado_por_id)');
        $this->addSql('CREATE TABLE tipo_caducidad (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_b8856b6ff6167a1c ON tipo_caducidad (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_b8856b6ffe35d8c4 ON tipo_caducidad (creado_por_id)');
        $this->addSql('CREATE TABLE tema (id INT NOT NULL, rama_id INT NOT NULL, tema_padre_id INT DEFAULT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, titulo VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_61e3a5385e0bfd3b ON tema (rama_id)');
        $this->addSql('CREATE INDEX idx_61e3a538fe35d8c4 ON tema (creado_por_id)');
        $this->addSql('CREATE INDEX idx_61e3a538c958426f ON tema (tema_padre_id)');
        $this->addSql('CREATE INDEX idx_61e3a538f6167a1c ON tema (actualizado_por_id)');
        $this->addSql('CREATE TABLE web_digesto_documento (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, titulo VARCHAR(255) NOT NULL, grupo VARCHAR(255) DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, nombre_documento VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_b7a67a7ffe35d8c4 ON web_digesto_documento (creado_por_id)');
        $this->addSql('CREATE INDEX idx_b7a67a7ff6167a1c ON web_digesto_documento (actualizado_por_id)');
        $this->addSql('CREATE TABLE web_digesto_documento_anexo (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, web_digesto_documento_id INT DEFAULT NULL, titulo VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, nombre_documento_anexo VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_a641aa86d3897d4b ON web_digesto_documento_anexo (web_digesto_documento_id)');
        $this->addSql('CREATE INDEX idx_a641aa86fe35d8c4 ON web_digesto_documento_anexo (creado_por_id)');
        $this->addSql('CREATE INDEX idx_a641aa86f6167a1c ON web_digesto_documento_anexo (actualizado_por_id)');
        $this->addSql('CREATE TABLE web_digesto_texto (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, prologo TEXT DEFAULT NULL, resenia TEXT DEFAULT NULL, metodologia_trabajo TEXT DEFAULT NULL, renumeracion TEXT DEFAULT NULL, instructivo_informativo TEXT DEFAULT NULL, contacto_facebook VARCHAR(255) DEFAULT NULL, contacto_instagram VARCHAR(255) DEFAULT NULL, contacto_twitter VARCHAR(255) DEFAULT NULL, contacto_mail VARCHAR(255) DEFAULT NULL, contacto_telefono VARCHAR(255) DEFAULT NULL, contacto_direccion VARCHAR(255) DEFAULT NULL, contacto_horario_atencion VARCHAR(255) DEFAULT NULL, presidente_hcd VARCHAR(255) DEFAULT NULL, director_digesto VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, nombre_archivo_foto_presidente VARCHAR(255) DEFAULT NULL, nombre_archivo_foto_director VARCHAR(255) DEFAULT NULL, vice_presidente_primero_hcd VARCHAR(255) DEFAULT NULL, nombre_archivo_foto_vice_presidente_primero VARCHAR(255) DEFAULT NULL, vice_presidente_segundo_hcd VARCHAR(255) DEFAULT NULL, nombre_archivo_foto_vice_presidente_segundo VARCHAR(255) DEFAULT NULL, vice_presidente_primero_cargo VARCHAR(255) DEFAULT NULL, vice_presidente_segundo_cargo VARCHAR(255) DEFAULT NULL, director_cargo VARCHAR(255) DEFAULT NULL, presidente_cargo VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_cd626c6af6167a1c ON web_digesto_texto (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_cd626c6afe35d8c4 ON web_digesto_texto (creado_por_id)');
        $this->addSql('CREATE TABLE anexo_norma (id INT NOT NULL, norma_id INT DEFAULT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, titulo VARCHAR(255) DEFAULT NULL, fecha DATE DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, archivo VARCHAR(255) NOT NULL, orden INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_2440d254f6167a1c ON anexo_norma (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_2440d254fe35d8c4 ON anexo_norma (creado_por_id)');
        $this->addSql('CREATE INDEX idx_2440d254e06fc29e ON anexo_norma (norma_id)');
        $this->addSql('CREATE TABLE identificador_norma (id INT NOT NULL, norma_id INT NOT NULL, identificador_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_29c6dd41e06fc29e ON identificador_norma (norma_id)');
        $this->addSql('CREATE INDEX idx_29c6dd41fe35d8c4 ON identificador_norma (creado_por_id)');
        $this->addSql('CREATE INDEX idx_29c6dd41f6167a1c ON identificador_norma (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_29c6dd41bfd0b734 ON identificador_norma (identificador_id)');
        $this->addSql('CREATE TABLE tipo_estado_norma (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_875ef98cfe35d8c4 ON tipo_estado_norma (creado_por_id)');
        $this->addSql('CREATE INDEX idx_875ef98cf6167a1c ON tipo_estado_norma (actualizado_por_id)');
        $this->addSql('CREATE TABLE tipo_promulgacion (id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_f8bd80a8f6167a1c ON tipo_promulgacion (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_f8bd80a8fe35d8c4 ON tipo_promulgacion (creado_por_id)');
        $this->addSql('CREATE TABLE beneficiario_norma (id INT NOT NULL, norma_id INT NOT NULL, beneficiario_id INT NOT NULL, creado_por_id INT DEFAULT NULL, actualizado_por_id INT DEFAULT NULL, activo BOOLEAN DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_b43f3af4fe35d8c4 ON beneficiario_norma (creado_por_id)');
        $this->addSql('CREATE INDEX idx_b43f3af4f6167a1c ON beneficiario_norma (actualizado_por_id)');
        $this->addSql('CREATE INDEX idx_b43f3af4e06fc29e ON beneficiario_norma (norma_id)');
        $this->addSql('CREATE INDEX idx_b43f3af44b64abc7 ON beneficiario_norma (beneficiario_id)');
        $this->addSql('ALTER TABLE anexo_consolidacion ADD CONSTRAINT fk_29c9d32c56f6e268 FOREIGN KEY (consolidacion_id) REFERENCES consolidacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE anexo_consolidacion ADD CONSTRAINT fk_29c9d32cf6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE anexo_consolidacion ADD CONSTRAINT fk_29c9d32cfe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cambio_anexo ADD CONSTRAINT fk_a711720256f6e268 FOREIGN KEY (consolidacion_id) REFERENCES consolidacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cambio_anexo ADD CONSTRAINT fk_a7117202e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE caducidad ADD CONSTRAINT fk_5aebd4213e118c56 FOREIGN KEY (tipo_caducidad_id) REFERENCES tipo_caducidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE caducidad ADD CONSTRAINT fk_5aebd42156f6e268 FOREIGN KEY (consolidacion_id) REFERENCES consolidacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE caducidad ADD CONSTRAINT fk_5aebd421e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE adhesiones ADD CONSTRAINT fk_efbedb9453347b49 FOREIGN KEY (tipo_norma_adhesion_id) REFERENCES tipo_norma_adhesion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE adhesiones ADD CONSTRAINT fk_efbedb94e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE adhesiones ADD CONSTRAINT fk_efbedb94f6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE adhesiones ADD CONSTRAINT fk_efbedb94fe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE anexo_original_norma ADD CONSTRAINT fk_7695817fe06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE anexo_original_norma ADD CONSTRAINT fk_7695817ff6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE anexo_original_norma ADD CONSTRAINT fk_7695817ffe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abrogacion ADD CONSTRAINT fk_abe8f69156f6e268 FOREIGN KEY (consolidacion_id) REFERENCES consolidacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abrogacion ADD CONSTRAINT fk_abe8f69163d6954a FOREIGN KEY (norma_abrogante_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abrogacion ADD CONSTRAINT fk_abe8f691e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE articulo_suprimido ADD CONSTRAINT fk_50f5bdaf56f6e268 FOREIGN KEY (consolidacion_id) REFERENCES consolidacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE articulo_suprimido ADD CONSTRAINT fk_50f5bdafe06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estado_norma ADD CONSTRAINT fk_340da78c56f6e268 FOREIGN KEY (consolidacion_id) REFERENCES consolidacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estado_norma ADD CONSTRAINT fk_340da78c9f5a440b FOREIGN KEY (estado_id) REFERENCES tipo_estado_norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estado_norma ADD CONSTRAINT fk_340da78ce06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE identificador ADD CONSTRAINT fk_a82558811a0c582f FOREIGN KEY (tipo_identificador_id) REFERENCES tipo_identificador (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE norma_consolidacion ADD CONSTRAINT fk_c3caedc856f6e268 FOREIGN KEY (consolidacion_id) REFERENCES consolidacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE norma_consolidacion ADD CONSTRAINT fk_c3caedc8e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE norma_consolidacion ADD CONSTRAINT fk_c3caedc8f6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE norma_consolidacion ADD CONSTRAINT fk_c3caedc8fe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE norma ADD CONSTRAINT fk_3ef6217e3c66e029 FOREIGN KEY (tipo_boletin_id) REFERENCES tipo_boletin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE norma ADD CONSTRAINT fk_3ef6217e3f799e6a FOREIGN KEY (tipo_promulgacion_id) REFERENCES tipo_promulgacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE norma ADD CONSTRAINT fk_3ef6217e5e0bfd3b FOREIGN KEY (rama_id) REFERENCES rama (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE norma ADD CONSTRAINT fk_3ef6217e82f348f1 FOREIGN KEY (rama_vigente_no_consolidada_id) REFERENCES rama (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE norma ADD CONSTRAINT fk_3ef6217e89500f1d FOREIGN KEY (tipo_ordenanza_id) REFERENCES tipo_ordenanza (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE norma ADD CONSTRAINT fk_3ef6217e934d3676 FOREIGN KEY (boletin_oficial_municipal_id) REFERENCES boletin_oficial_municipal (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE norma ADD CONSTRAINT fk_3ef6217eaf03385e FOREIGN KEY (tipo_veto_id) REFERENCES tipo_veto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consolidacion ADD CONSTRAINT fk_f22af2bdf6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consolidacion ADD CONSTRAINT fk_f22af2bdfe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cambio_norma ADD CONSTRAINT fk_5499fc5056f6e268 FOREIGN KEY (consolidacion_id) REFERENCES consolidacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cambio_norma ADD CONSTRAINT fk_5499fc50e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE palabra_clave_norma ADD CONSTRAINT fk_58f066a97e0cd09e FOREIGN KEY (palabra_clave_id) REFERENCES palabra_clave (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE palabra_clave_norma ADD CONSTRAINT fk_58f066a9e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE conflicto_normativo ADD CONSTRAINT fk_90e7d3f056f6e268 FOREIGN KEY (consolidacion_id) REFERENCES consolidacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE conflicto_normativo ADD CONSTRAINT fk_90e7d3f0c60326cb FOREIGN KEY (conflicto_con_norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE conflicto_normativo ADD CONSTRAINT fk_90e7d3f0e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE conflicto_normativo ADD CONSTRAINT fk_90e7d3f0f6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE conflicto_normativo ADD CONSTRAINT fk_90e7d3f0fe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE descriptor_norma ADD CONSTRAINT fk_9a9beef02a13d45 FOREIGN KEY (descriptor_id) REFERENCES descriptor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE descriptor_norma ADD CONSTRAINT fk_9a9beef0e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE observacion_antecedente ADD CONSTRAINT fk_9ed78a2956f6e268 FOREIGN KEY (consolidacion_id) REFERENCES consolidacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE observacion_antecedente ADD CONSTRAINT fk_9ed78a29e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fundamentacion ADD CONSTRAINT fk_e1813ae656f6e268 FOREIGN KEY (consolidacion_id) REFERENCES consolidacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fundamentacion ADD CONSTRAINT fk_e1813ae6e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tema_norma ADD CONSTRAINT fk_69ff1705a64a8a17 FOREIGN KEY (tema_id) REFERENCES tema (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tema_norma ADD CONSTRAINT fk_69ff1705e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_identificador ADD CONSTRAINT fk_a8960bdff6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_identificador ADD CONSTRAINT fk_a8960bdffe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refundicion ADD CONSTRAINT fk_cbfa0e8d56f6e268 FOREIGN KEY (consolidacion_id) REFERENCES consolidacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refundicion ADD CONSTRAINT fk_cbfa0e8d99305259 FOREIGN KEY (norma_refundida_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refundicion ADD CONSTRAINT fk_cbfa0e8de06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refundicion ADD CONSTRAINT fk_cbfa0e8df6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refundicion ADD CONSTRAINT fk_cbfa0e8dfe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_boletin ADD CONSTRAINT fk_76e9dfddf6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_boletin ADD CONSTRAINT fk_76e9dfddfe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_ordenanza ADD CONSTRAINT fk_46bcfab5f6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_ordenanza ADD CONSTRAINT fk_46bcfab5fe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_veto ADD CONSTRAINT fk_bd7d3ee9f6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_veto ADD CONSTRAINT fk_bd7d3ee9fe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_norma_adhesion ADD CONSTRAINT fk_537c3f2bf6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_norma_adhesion ADD CONSTRAINT fk_537c3f2bfe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_caducidad ADD CONSTRAINT fk_b8856b6ff6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_caducidad ADD CONSTRAINT fk_b8856b6ffe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tema ADD CONSTRAINT fk_61e3a5385e0bfd3b FOREIGN KEY (rama_id) REFERENCES rama (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tema ADD CONSTRAINT fk_61e3a538c958426f FOREIGN KEY (tema_padre_id) REFERENCES tema (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tema ADD CONSTRAINT fk_61e3a538f6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tema ADD CONSTRAINT fk_61e3a538fe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE web_digesto_documento ADD CONSTRAINT fk_b7a67a7ff6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE web_digesto_documento ADD CONSTRAINT fk_b7a67a7ffe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE web_digesto_documento_anexo ADD CONSTRAINT fk_a641aa86d3897d4b FOREIGN KEY (web_digesto_documento_id) REFERENCES web_digesto_documento (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE web_digesto_documento_anexo ADD CONSTRAINT fk_a641aa86f6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE web_digesto_documento_anexo ADD CONSTRAINT fk_a641aa86fe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE web_digesto_texto ADD CONSTRAINT fk_cd626c6af6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE web_digesto_texto ADD CONSTRAINT fk_cd626c6afe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE anexo_norma ADD CONSTRAINT fk_2440d254e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE identificador_norma ADD CONSTRAINT fk_29c6dd41bfd0b734 FOREIGN KEY (identificador_id) REFERENCES identificador (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE identificador_norma ADD CONSTRAINT fk_29c6dd41e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_estado_norma ADD CONSTRAINT fk_875ef98cf6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_estado_norma ADD CONSTRAINT fk_875ef98cfe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_promulgacion ADD CONSTRAINT fk_f8bd80a8f6167a1c FOREIGN KEY (actualizado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_promulgacion ADD CONSTRAINT fk_f8bd80a8fe35d8c4 FOREIGN KEY (creado_por_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE beneficiario_norma ADD CONSTRAINT fk_b43f3af44b64abc7 FOREIGN KEY (beneficiario_id) REFERENCES beneficiario (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE beneficiario_norma ADD CONSTRAINT fk_b43f3af4e06fc29e FOREIGN KEY (norma_id) REFERENCES norma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE paciente');
        $this->addSql('DROP TABLE orden_medica');
        $this->addSql('ALTER TABLE area_administrativa ADD dependencia_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE area_administrativa ADD CONSTRAINT fk_25706caddf2432b6 FOREIGN KEY (dependencia_id) REFERENCES dependencia (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX uniq_25706caddf2432b6 ON area_administrativa (dependencia_id)');
        $this->addSql('ALTER TABLE expediente DROP marca_temporal');
        $this->addSql('ALTER TABLE expediente DROP hash');
        $this->addSql('ALTER TABLE expediente DROP marca_definitivo');
        $this->addSql('ALTER TABLE personal_articulo DROP dias');
        $this->addSql('ALTER TABLE fos_user ADD area_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fos_user ALTER roles TYPE TEXT');
        $this->addSql('ALTER TABLE fos_user ALTER roles DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN fos_user.roles IS \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE fos_user ADD CONSTRAINT fk_957a6479bd0f409c FOREIGN KEY (area_id) REFERENCES area_administrativa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_957a6479bd0f409c ON fos_user (area_id)');
    }
}
